apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertising-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: advertising
  template:
    metadata:
      labels:
        app: advertising
    spec:
      containers:
        - name: advertising
          image: sathwik10/advertising2
          ports:
            - containerPort: 5000
